### ISSUE TITLE
“Touch the clock area to stop recording.” is misleading,actually u should click battery icon to stop recording

### ISSUE THREAD

**Issue by mzq729019** [JakeWharton/Telecine#81] opened 2015-11-04 03:46 UTC
![device-2015-11-04-113922](https://cloud.githubusercontent.com/assets/5887977/10929018/20a4660e-82e9-11e5-89bc-f5cf33a392f7.png)

In my Nexus 6 and another test phone which I dont know its type ,Touch the clock area will not stop recording,but click the red area will work
@JakeWharton ,maybe edit the illustration?

**Comment by JakeWharton** [comment] 2015-11-04 09:12
The highlighted area in your photo is not accurate. It's the same width and height as the overlay that appears in the upper-right corner.

**Comment by quentin41500** [comment] 2016-05-16 15:24
@mzq729019 if you want to see where the area is exactly, I suggest you display layout bounds in developer settings. Here is a short explanation on how to enable it https://androidthoughts.wordpress.com/2014/08/18/settings-show-layout-bounds/.

**Comment by jaredsburrows** [comment] 2016-06-14 06:05
@mzq729019 What is your solution for this? Adding a visible element would be recorded.

**Comment by JakeWharton** [comment] 2016-08-26 22:52
Closing as a duplicate of #2 and a user education problem.

**Closed by JakeWharton** 2016-08-26 22:52 UTC
