### ISSUE TITLE
Can't stop recording (and save) on Android 8

### ISSUE THREAD

**Issue by comsraynal** [JakeWharton/Telecine#181] opened 2018-05-23 05:47 UTC
On Android 8, it is impossible to click on the red button to stop recording and save.

The Android drop down menu takes the focus, somehow disabling the button.

The application is otherwise a wonder, nice job!

**Comment by JakeWharton** [comment] 2018-05-23 15:03
Duplicate of #149.

**Closed by JakeWharton** 2018-05-23 15:03 UTC
