### ISSUE TITLE
Can i Record Video Specific View or part

### ISSUE THREAD

**Issue by mehulTank** [JakeWharton/Telecine#183] opened 2018-10-01 13:11 UTC
This library is good but i have one query is can i record a video any specific view or half of screen ?
if yes can please let me know.

**Comment by JakeWharton** [comment] 2018-10-01 13:12
This is not supported yet, no. Dupe of #42.

**Closed by JakeWharton** 2018-10-01 13:12 UTC

**Comment by mehulTank** [comment] 2018-10-01 13:53
Thanks
