### ISSUE TITLE
Screen refresh rate slows to a crawl AFTER using Telecine

### ISSUE THREAD

**Issue by marcardar** [JakeWharton/Telecine#65] opened 2015-07-26 04:06 UTC
On a rooted LG G3 DUAL (LG-D858HK, LRX22G) Android 5.0, if I run Telecine, record a video and stop the video then turn off the screen (either manually or let it timeout), then after the screen is turned back on, and after some more time (variable, but usually minutes), the screen refresh rate becomes very jerky, gradually gets worse and the only way to get back to normal is to reboot the device. Force Stop on Telecine does not help.

Interestingly, if the screen goes off while the device is being charged, then the problem does not occur.

If I run the app while plugged in and Force Stop while still plugged in, then unplug, the refresh issue is still a problem.

Take Bug Report not working on this device, unfortunately, and I don't have access to the device generally.

Any ideas what _could_ be causing this?

**Comment by JakeWharton** [comment] 2015-07-26 04:21
My guess would be an Android operating system bug that causes problems when the `MediaProjection` API is used. Telecine doesn't really do all that much when it comes to recording... we really just hook up Android's media recorder to its media projector and point it at a file.

There are a few other screen recording apps in the Play Store which use the same technique. I would suggest trying one and seeing if the same thing happens. I don't know one off-hand because, well, I use Telecine!

**Comment by marcardar** [comment] 2015-07-26 04:24
Yeah, my app also exhibits the same problem. But so far, only on that device. So I agree it's probably a bug specific to that device. Having said that, it's passed CTS and it running Google Play, so it *should* work. Just curious if you have any ideas what it *might* be?  The "plugged in" difference might indicate it's to do with whether the device goes to a deeper stand by mode, for example.

**Comment by JakeWharton** [comment] 2015-07-26 04:29
I'm not sure if we have the device, I'll have to check. Even in that case, the problem is surely buried in the native code which deals with rendering to the real and fake displays which are likely nearly impossible to debug. I'll check this week though which at least might allow me to confirm the bug's existence by reproduction.

> it's passed CTS

I think you are over-estimating CTS! It's pretty awful what OEMs can get away with breaking. The word "Samsung" comes to mind...

**Comment by marcardar** [comment] 2015-07-26 04:32
Cool, thanks. FWIW I added the issue to the main tracker: https://code.google.com/p/android/issues/detail?id=181207

**Comment by JakeWharton** [comment] 2016-12-08 05:59
Closing the issue, but following the reported one. Thanks.

**Closed by JakeWharton** 2016-12-08 05:59 UTC
