### ISSUE TITLE
Bug found while close the tab on telecine.

### ISSUE THREAD

**Issue by maliksajad12** [JakeWharton/Telecine#175] opened 2018-02-27 12:36 UTC
Expected behavior

In this application the tab should be closed while I starting video as it closes like in the other apps during video.

Actual behavior

We are not able to close this tab during video as it shows some unknown error occurred.

How to reproduce

Download the app.

Open the app.

Click on red video bar right corner below option.

Click on start now.

See in the right top there is an x and red colour video bar.

Then I click on  'x' close bar, unknown error occurred.

* App: Telecine- version 1.6.2
* Operating system: mi A1 8.0 "Oreo"

Recording Of The Bug

https://youtu.be/urFORUKj5QA    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@maliksajad/bug-found-while-close-the-tab-on-telecine">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by JakeWharton** [comment] 2018-02-27 13:43
Dupe of #149.

**Closed by JakeWharton** 2018-02-27 13:43 UTC
