### ISSUE TITLE
Can't press the buttons on the overlay

### ISSUE THREAD

**Issue by ShaunDreclin** [JakeWharton/Telecine#180] opened 2018-05-06 19:09 UTC
They seem to show up under the system clock, and if I tap them it just pulls down the notification menu

![screenshot](https://user-images.githubusercontent.com/5851433/39676883-c5c2d05e-513f-11e8-8d07-392082bc3712.jpg)

**Comment by JakeWharton** [comment] 2018-05-06 19:12
Dupe of #149. Unfortunate change in the OS.

**Closed by JakeWharton** 2018-05-06 19:12 UTC

**Comment by ShaunDreclin** [comment] 2018-05-06 19:14
Oh yikes that issue is over a year old, is a fix not coming?
