### ISSUE TITLE
stably crashed on running device before API 23 due to Dagger

### ISSUE THREAD

**Issue by TonyTangAndroid** [JakeWharton/Telecine#170] opened 2018-02-02 23:34 UTC
Here is the stack trace: 

> FATAL EXCEPTION: main
                                                 Process: com.jakewharton.telecine.debug, PID: 3870
                                                 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jakewharton/telecine/TelecineTileService;
                                                     at com.jakewharton.telecine.DaggerTelecineComponent.initialize(DaggerTelecineComponent.java:192)
                                                     at com.jakewharton.telecine.DaggerTelecineComponent.<init>(DaggerTelecineComponent.java:97)
                                                     at com.jakewharton.telecine.DaggerTelecineComponent.<init>(DaggerTelecineComponent.java:20)
                                                     at com.jakewharton.telecine.DaggerTelecineComponent$Builder.build(DaggerTelecineComponent.java:277)
                                                     at com.jakewharton.telecine.TelecineApplication.onCreate(TelecineApplication.java:22)
                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
                                                     at android.app.ActivityThread.-wrap1(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jakewharton.telecine.TelecineTileService" on path:

**Comment by TonyTangAndroid** [comment] 2018-02-03 00:34
The root cause is because in pre-nougat device, there is no service as TileService.java.

**Comment by NightlyNexus** [comment] 2018-02-03 00:52
Is this on the latest master? I probably messed it up when playing with the Dagger-Android pieces.

**Comment by TonyTangAndroid** [comment] 2018-02-03 00:54
Yes, this is the latest master.

**Comment by JakeWharton** [comment] 2018-02-03 10:23
Dupe of #166

**Closed by JakeWharton** 2018-02-03 10:23 UTC
