### ISSUE TITLE
The status of the recording occludes the taskbar

### ISSUE THREAD

**Issue by lifesaver0129** [JakeWharton/Telecine#184] opened 2018-12-22 09:27 UTC
Link to the issue: [here](https://github.com/JakeWharton/Telecine/issues/184)

**Describe the bug**
The status of the recording occludes the taskbar

**Context**
Device: Pixel 2 XL API 27
OS Version: Android 8.1.0
App version: 1.6.2

**How to reproduce**
1.  Open the application
2.  Start recording
3.  The status of the recording occludes the taskbar

**Expected Behavior**
The record status should be somewhere else instead of covering the other icons

**Screenshots**
<p align="center">
    <img src="https://user-images.githubusercontent.com/26133021/50372738-d129d800-060e-11e9-9caa-aa210c05b583.png"  width="200" height="400">
    <p align="center">
        <em>Step 3</em>
    </p>
</p>
</p>

**Comment by mattprecious** [comment] 2018-12-23 02:42
Dupe of #149.

**Comment by lifesaver0129** [comment] 2018-12-23 08:00
> Dupe of #149.

Is #149 API 27 as well?

**Comment by JakeWharton** [comment] 2018-12-24 05:08
O is 26 and up, yes.

**Closed by JakeWharton** 2018-12-24 05:08 UTC
