### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jakewharton/telecine/TelecineTileService;

### ISSUE THREAD

**Issue by aviontechnology** [JakeWharton/Telecine#173] opened 2018-02-20 06:25 UTC
i am facing some issue with sample

FATAL EXCEPTION: main
                  Process: com.jakewharton.telecine.debug, PID: 2626
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jakewharton/telecine/TelecineTileService;
                      at com.jakewharton.telecine.DaggerTelecineComponent.initialize(DaggerTelecineComponent.java:192)
                      at com.jakewharton.telecine.DaggerTelecineComponent.<init>(DaggerTelecineComponent.java:97)
                      at com.jakewharton.telecine.DaggerTelecineComponent.<init>(DaggerTelecineComponent.java:20)
                      at com.jakewharton.telecine.DaggerTelecineComponent$Builder.build(DaggerTelecineComponent.java:277)
                      at com.jakewharton.telecine.TelecineApplication.onCreate(TelecineApplication.java:22)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4579)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:135)
                      at android.app.ActivityThread.main(ActivityThread.java:5280)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jakewharton.telecine.TelecineTileService" on path: DexPathList[[zip file "/data/app/com.jakewharton.telecine.debug-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at com.jakewharton.telecine.DaggerTelecineComponent.initialize(DaggerTelecineComponent.java:192) 
                      at com.jakewharton.telecine.DaggerTelecineComponent.<init>(DaggerTelecineComponent.java:97) 
                      at com.jakewharton.telecine.DaggerTelecineComponent.<init>(DaggerTelecineComponent.java:20) 
                      at com.jakewharton.telecine.DaggerTelecineComponent$Builder.build(DaggerTelecineComponent.java:277) 
                      at com.jakewharton.telecine.TelecineApplication.onCreate(TelecineApplication.java:22) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4579) 
                      at android.app.ActivityThread.access$1500(ActivityThread.java:151) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:135) 
                      at android.app.ActivityThread.main(ActivityThread.java:5280) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
                  	Suppressed: java.lang.NoClassDefFoundError: com.jakewharton.telecine.TelecineTileService
                      at dalvik.system.DexFile.defineClassNative(Native Method)
                      at dalvik.system.DexFile.defineClass(DexFile.java:226)
                      at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                      at dalvik.system.DexPathList.findClass(DexPathList.java:321)
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                      		... 18 more
                  	Suppressed: java.lang.ClassNotFoundException: com.jakewharton.telecine.TelecineTileService
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 17 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by NightlyNexus** [comment] 2018-02-20 06:43
Duplicate of #166

**Closed** 2018-02-20 13:07 UTC
